version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DBUSER}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
    ports:
      - '${DBPORT}:${DBPORT}'
    volumes: 
      - db:/var/lib/postgresql/data
  userserv:
    build: ./userserv
    ports:
      - '${USERSERVPORT}:${USERSERVPORT}'
    depends_on:
      - db
    links:
      - db 
    environment:
      - DBHOST=${DBHOST}
      - DBPORT=${DBPORT}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBNAME=${DBNAME}
  gateway:
    build: ./gateway
    ports:
      - '${GATEWAYPORT}:${GATEWAYPORT}'
    depends_on:
      - userserv
    links:
      - userserv 
    environment:
      - GATEWAYPORT=${GATEWAYPORT}
      - USERSERVURI=http://userserv:${USERSERVPORT}/api
  web:
    build: 
      context: ./web
      args:
      - APIURL=http://gateway:${GATEWAYPORT} 
    ports:
      - '${WEBPORT}:${WEBPORT}'
    depends_on:
      - gateway
    links:
      - gateway    
volumes:
  db:
    driver: local